image:
  repository: europe-west3-docker.pkg.dev/argon-tuner-396010/fulfillai/fulfillai-api
  tag: f71e76450e7d0754fa7971237f93cd5623ddfca8
  digest: sha256:7ec5f73e9d3f2c4b45838014df6a5de4f77a3607cee04a8a3f4afc98b2d9bc93
serviceAccount:
  gcpServiceAccount: fulfillai-api@argon-tuner-396010.iam.gserviceaccount.com
