apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: fulfillai
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - fulfillai
  selector:
    matchLabels:
      app.kubernetes.io/name: fulfillai
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
