apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fulfillai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nikchey29/fulfillai.git
    targetRevision: platform-engineering-v2
    path: deploy/helm/fulfillai
    helm:
      valueFiles:
        - values-gitops.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fulfillai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
