input {
  http {
    port => 8080
    codec => json
  }
}

filter {
  if ![service] {
    mutate { add_field => { "service" => "fulfillai-api" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "fulfillai-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
