apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fulfillai
  labels:
    app.kubernetes.io/name: fulfillai
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "fulfillai"
